title:              RS Counselling
email:              talk@rscounselling.com
description:        A step towards a better you.
author:             Reni Sharma
baseurl:            ""
url:                "http://rscounselling.github.io/"
logo:               "/img/tea_cup_small.png"

# Social Profiles
# twitter_username:   rs.counselling
# github_username:    BlackrockDigital
# facebook_username:  StartBootstrap
linkedin_username:    renikasharma
instagram_username:   rs.counselling

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
highlighter:        rouge
kramdown:
   input: GFM #Github Flavored Markdown
   hard_wrap: false  
   syntax_highlighter: rouge
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
